name: Publish to NPM

on:
  push:
    branches:
      - main
#    tags:
#      - 'v*' # Triggers on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allows manual triggering

env:
  CI: true
  NODE_VERSION: '20' # Using LTS version

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies and run tests
      run: npm install && npm run jest --rootDir=.
      env:
        ALLOW_MOCK_TEMPLATES: 'true'
    
    - name: Run build
      run: npm run build

  publish-npm:
    name: Publish to NPM
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
