name: Publish to NPM

on:
  push:
    branches:
      - main
#    tags:
#      - 'v*' # Triggers on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allows manual triggering

env:
  CI: true
  NODE_VERSION: '20' # Using LTS version

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies and run tests
      run: npm install && npm run test
      env:
        ALLOW_MOCK_TEMPLATES: 'true'
    
    - name: Run build
      run: npm run build

  release:
    needs: test
    permissions:
      contents: write
      packages: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@blacdot'

      - name: Install Dependencies
        run: npm install

      - name: Install semantic-release and plugins
        run: |
          npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/npm @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Build package
        run: npm run build
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ github.ref_name }}
          tag_name: v${{ github.ref_name }}
          body: |
            ## What's Changed
            - See the full changelog in CHANGELOG.md
            
            ### 🚀 Features
            - Add new features
            
            ### 🐛 Bug Fixes
            - Fix various issues
          files: |
            dist/*.js
            package.json
            README.md
            CHANGELOG.md
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Publish package to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Clean up the semantic-release packages installation
        run: |
          npm uninstall --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/npm @semantic-release/github